#!/usr/bin/with-contenv bash

if [ -n "$PASSWORD" ]; then
    echo "abc:${PASSWORD}" | chpasswd
    echo "**** Setting password from environment variable. ****"
else
    echo "**** No auth enabled. To enable auth, you can set the PASSWORD var in docker arguments. ****"
fi


if [ ! -d /cursor ]; then
    echo "**** Creating cursor folder. ****"
    mkdir -p /cursor;
fi

echo "********************************"
echo "****   Debug Information    ****"
echo "********************************"
echo ""
echo "********************************"
echo "**** Start Date Information ****"
echo "********************************"
echo "TZ: ${TZ}"
echo "Running dpkg-reconfigure -f noninteractive tzdata"
echo "${TZ}" >/etc/timezone
dpkg-reconfigure -f noninteractive tzdata
echo "Date UTC"
date --utc
echo "Date Local"
date
echo "Zone Info"
zdump /usr/share/zoneinfo/${TZ}
echo "Time Zone Offsets"
zdump -v /etc/localtime
echo "********************************"
echo "****  End Date Information  ****"
echo "********************************"

# permissions
chown -R abc:abc \
    /config \
    /cursor \
    /root
